# Generated by Django 5.0 on 2023-12-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidityreading',
            name='humidity',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='temperaturereading',
            name='temperature',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
